GET https://userbank-n.herokuapp.com/dados/55495000
###

PUT https://userbank-n.herokuapp.com/dados/update
Content-Type: application/json

{
    "nome": "Nata Lucas Silva",
    "cpf": "12313312312",
    "data_nascimento": "2002/02/10" ,
    "saldo": 550000,
    "limite": 50000000,
    "cep": "55555000",
    "logradouro": "Rua 1",
    "bairro": "Centro",
    "numero": "37",
    "cidade": "Caruaru",
    "uf": "PE"
}



###

GET https://userbank-case.herokuapp.com/usuarios

###

DELETE https://userbank-n.herokuapp.com/111111123111

###

PUT https://userbank-n.herokuapp.com/img 
Content-Type: application/json

{
    "cpf": "11111121111",
    "avatar_url": "alterada"
}
